    FROM golang:1.22.4-alpine AS builder

   
    WORKDIR /app
    
  
    COPY go.mod go.sum ./
    RUN go mod download
    
  
    COPY . .
    
    RUN go build -o /app/phala main.go
    

    FROM alpine:3.18
    

    COPY --from=builder /app/phala /usr/local/bin/phala
    COPY --from=builder /app/.env .
    COPY --from=builder /app/key.txt .

    ENTRYPOINT ["/usr/local/bin/phala"]
    