    FROM golang:1.22.4-alpine AS builder

   
    WORKDIR /app
    
  
    COPY go.mod go.sum ./
    RUN go mod download
    
  
    COPY . .
    
    RUN go build -o /app/myapp main.go
    

    FROM alpine:3.18
    

    COPY --from=builder /app/myapp /usr/local/bin/myapp
    COPY --from=builder /app/.env .
    COPY --from=builder /app/key.txt .

    ENTRYPOINT ["/usr/local/bin/myapp"]
    